name: Vercel Deploy

on:
  push:
    branches:
      - main
      - release
  pull_request:
    types:
      - closed
    branches:
      - main
      - release

jobs:
  deploy:
    # プルリクエストがマージされた時のみ実行する条件を追加
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          alias-domains: |
            ${{ github.ref == 'refs/heads/main' && 'dev.yoursite.com' || 'yoursite.com' }}
